# SPDX-FileCopyrightText: 2023 The Aalto Grades Developers
#
# SPDX-License-Identifier: MIT

FROM node:16-alpine as build
WORKDIR /app
COPY . .
RUN chown -R node:node ./
ARG REACT_APP_BACKEND_URL="http://backend"
ARG REACT_APP_BACKEND_PORT="3000"
RUN npm ci
RUN npm run build
USER node

FROM nginx:1.23.3-alpine
EXPOSE 80
COPY --from=build /app/build /user/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
CMD ["nginx", "-g", "daemon off;"] 
