# SPDX-FileCopyrightText: 2023 The Aalto Grades Developers
#
# SPDX-License-Identifier: MIT

# This Docker Compose file defines common configuration for use in all other
# Docker Compose files
---
version: '3.7'

services:
  frontend-common:
    build:
      context: .
      dockerfile: ./client/Dockerfile
    extends:
      service: frontend-minimum

  frontend-minimum:
    restart: always
    tty: true
    environment:
      VITE_APP_BACKEND_URL: ${AALTO_GRADES_FRONTEND_CORS_ORIGIN}
      VITE_APP_BACKEND_PORT: "443"
      # BACKEND_URL: 'backend' # If it is still commentend it is obsolete
      # BACKEND_PORT: '3000' # If it is still commentend it is obsolete
    networks:
      - local

  backend-common:
    build:
      context: .
      dockerfile: ./server/dockerfiles/Dockerfile
    extends:
      service: backend-minimum

  backend-common-test:
    build:
      context: .
      dockerfile: ./server/dockerfiles/Dockerfile.test
    extends:
      service: backend-minimum

  backend-minimum:
    tty: true
    environment:
      POSTGRES_URL: 'database'
      POSTGRES_USER: 'postgres'
      POSTGRES_DATABASE: 'postgres'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
    networks:
      - local

  database:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
    networks:
      - local

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    networks:
      - local
