# SPDX-FileCopyrightText: 2023 The Aalto Grades Developers
#
# SPDX-License-Identifier: MIT

# This Docker Compose file defines common configuration for use in all other
# Docker Compose files
---

version: "3.7"

services:
  frontend-common:
    build:
      context: .
      dockerfile: ./client/Dockerfile
    extends:
      service: frontend-minimum

  frontend-minimum:
    restart: always
    tty: true
    environment:
      BACKEND_URL: "backend"
      BACKEND_PORT: "3000"
    networks:
      - local

  backend-common:
    build:
      context: .
      dockerfile: ./server/dockerfiles/Dockerfile
    extends:
      service: backend-minimum

  backend-commontest:
    build:
      context: .
      dockerfile: ./server/dockerfiles/Dockerfile.test
    extends:
      service: backend-minimum

  backend-minimum:
    tty: true
    environment:
      POSTGRES_URL: "database"
      POSTGRES_USER: "postgres"
      POSTGRES_DATABASE: "postgres"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      SISU_API_KEY: "${SISU_API_KEY}"
      SISU_API_URL: "${SISU_API_URL}"
    networks:
      - local

  database:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    networks:
      - local

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    networks:
      - local
