# SPDX-FileCopyrightText: 2022 The Aalto Grades Developers
#
# SPDX-License-Identifier: MIT

version: "3.9"

services:

  front-end:
    build: ./client
    restart: always
    ports:
    - "3005:3005"
    container_name: frontend-server
    networks:
      - local

  back-end:
    build: ./server
    restart: always
    ports:
    - "3000:3000"
    container_name: backend-server
    networks:
      - local

  database:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: tester
    networks:
      - local

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - local

networks:
  local:
    driver: bridge