# SPDX-FileCopyrightText: 2022 The Aalto Grades Developers
#
# SPDX-License-Identifier: MIT

# This is a Docker Compose configuration for running Aalto Grades locally,

---
services:
  reverse-proxy:
    image: nginx:1.27-alpine
    container_name: aalto-grades-reverse-proxy-dev
    ports:
      - 8080:80
    volumes:
      - ./reverse-proxy-dev.conf:/etc/nginx/nginx.conf

  frontend:
    build:
      context: .
      dockerfile: ./client/Dockerfile
    container_name: aalto-grades-frontend-dev

  backend:
    build:
      context: .
      dockerfile: ./server/dockerfiles/Dockerfile
    container_name: aalto-grades-backend-dev
    environment:
      POSTGRES_URL: 'database'
      POSTGRES_USER: 'postgres'
      POSTGRES_DATABASE: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
    depends_on:
      - database

  database:
    image: postgres:15
    container_name: aalto-grades-database-dev
    ports:
      - 5432:5432 # Exposed for e2e tests to work
    environment:
      POSTGRES_PASSWORD: 'postgres'
