# SPDX-FileCopyrightText: 2024 The Ossi Developers
#
# SPDX-License-Identifier: MIT

# This is a Docker Compose configuration for deploying Ossi to a
# virtual machine from the dev branch. Requires correct setup work to be done
# on the VM. Documentation for deployment is available in the aalto wiki.

---
services:
  reverse-proxy:
    extends:
      file: ./docker-compose-from-images.yaml
      service: reverse-proxy
    depends_on:
      - frontend
      - backend

  frontend:
    extends:
      file: ./docker-compose-from-images.yaml
      service: frontend
    image: ghcr.io/aalto-grades/aalto-grades-frontend:canary

  backend:
    extends:
      file: ./docker-compose-from-images.yaml
      service: backend
    image: ghcr.io/aalto-grades/aalto-grades-backend:canary
    environment:
      OTEL_SERVICE_NAME: "ossi-test-backend"

  database:
    extends:
      file: ./docker-compose-from-images.yaml
      service: database

  otel-lgtm:
    extends:
      file: ./docker-compose-from-images.yaml
      service: otel-lgtm
    volumes:
      - "./grafana_volume/data:/data"
    environment:
      - OTEL_RESOURCE_ATTRIBUTES=service.name=otel-lgtm-dev
