# SPDX-FileCopyrightText: 2023 The Aalto Grades Developers
#
# SPDX-License-Identifier: MIT

# This is a Docker Compose configuration for deploying Aalto Grades to a
# virtual machine. Requires correct setup work to be done on the VM.
# Documentation for deployment is available in the VM's root user's deployment
# folder.
---

version: "3.7"

services:

  reverse-proxy:
    build:
      context: ./reverse-proxy
      args:
        CERT_FILE: "${CERT_FILE}"
        CERT_KEY_FILE: "${CERT_KEY_FILE}"
    restart: always
    container_name: reverse-proxy
    ports:
      - 443:443
      - 80:80
    networks:
      - local

  frontend:
    extends:
      file: ./common-services.yaml
      service: frontend-minimum
    image: ghcr.io/aalto-grades/aalto-grades-frontend:main
    container_name: frontend-server

  backend:
    extends:
      file: ./common-services.yaml
      service: backend-minimum
      args:
        SAML_DECRYPTION_PVK_FILE: "${SAML_DECRYPTION_PVK_FILE}"
        SAML_PRIVATE_KEY_FILE: "${SAML_PRIVATE_KEY_FILE}"
        SAML_SP_CERT_FILE: "${SAML_SP_CERT_FILE}"
    build:
      context: .
      dockerfile: ./server/dockerfiles/Dockerfile.prod.run
    container_name: backend-server
    environment:
      AALTO_GRADES_BACKEND_PORT: "${AALTO_GRADES_BACKEND_PORT}"
      AALTO_GRADES_FRONTEND_CORS_ORIGIN: "${AALTO_GRADES_FRONTEND_CORS_ORIGIN}"
      AALTO_GRADES_JWT_SECRET: "${AALTO_GRADES_JWT_SECRET}"
      APLUS_API_URL: "${APLUS_API_URL}"
      SAML_CALLBACK: "${SAML_CALLBACK}"
      SAML_ENTRYPOINT: "${SAML_ENTRYPOINT}"
      SAML_ISSUER: "${SAML_ISSUER}"
      SAML_METADATA_URL: "${SAML_METADATA_URL}"
      NODE_ENV: "production"
    logging:
      driver: syslog
      options:
        syslog-address: "tcp://localhost:601"
        tag: "aalto-grades"

  database:
    extends:
      file: ./common-services.yaml
      service: database
    environment:
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ${POSTGRES_MOUNTDIR}:/var/lib/postgresql/data

networks:
  local:
    driver: bridge
