# SPDX-FileCopyrightText: 2023 The Aalto Grades Developers
#
# SPDX-License-Identifier: MIT

# This is a Docker Compose configuration for deploying Aalto Grades to a
# virtual machine from the dev branch. Requires correct setup work to be done
# on the VM. Documentation for deployment is available in the VM's root user's
# deployment folder.
---

version: "3.7"

services:

  reverse-proxy:
    extends:
      file: ./docker-compose-from-images.yaml
      service: reverse-proxy

  frontend:
    extends:
      file: ./docker-compose-from-images.yaml
      service: frontend
    image: ghcr.io/aalto-grades/aalto-grades-frontend-dev:dev

  backend:
    extends:
      file: ./docker-compose-from-images.yaml
      service: backend
    build:
      dockerfile: ./server/dockerfiles/Dockerfile.prod.run.dev

  database:
    extends:
      file: ./docker-compose-from-images.yaml
      servics: database

networks:
  local:
    driver: bridge
