# SPDX-FileCopyrightText: 2023 The Aalto Grades Developers
#
# SPDX-License-Identifier: MIT

version: "3.7"

services:

  reverse-proxy:
    build:
      context: ./reverse-proxy
    restart: always
    container_name: reverse-proxy
    ports:
    - 8080:80
    networks:
    - local

  frontend:
    extends:
      file: ./common-services.yaml
      service: frontend
    image: ghcr.io/aalto-grades/aalto-grades-frontend:deployment-configuration
    container_name: frontend-server

  backend:
    extends:
      file: ./common-services.yaml
      service: backend
    image: ghcr.io/aalto-grades/aalto-grades-backend:deployment-configuration
    container_name: backend-server
    environment:
      AALTO_GRADES_JWT_SECRET: "${AALTO_GRADES_JWT_SECRET}"
      AALTO_GRADES_FRONTEND_CORS_ORIGIN: "https://aalto-grades.cs.aalto.fi"

  database:
    extends:
      file: ./common-services.yaml
      service: database
      
networks:
  local:
    driver: bridge
