# SPDX-FileCopyrightText: 2022 The Aalto Grades Developers
#
# SPDX-License-Identifier: MIT

version: "3.7"

services:

  reverse-proxy:
    build:
      context: ./reverse-proxy
    restart: always
    container_name: reverse-proxy
    ports:
    - 8080:80
    networks:
    - local

  frontend:
    image: ghcr.io/aalto-grades/aalto-grades-frontend:deployment-configuration
    restart: always
    container_name: frontend-server
    environment:
      BACKEND_URL: "backend"
      BACKEND_PORT: "3000"
    networks:
      - local

  backend:
    image: ghcr.io/aalto-grades/aalto-grades-backend:deployment-configuration
    restart: always
    container_name: backend-server
    environment:
      POSTGRES_URL: "database"
      POSTGRES_USER: "postgres"
      POSTGRES_DATABASE: "postgres"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      SISU_API_KEY: "${SISU_API_KEY}"
      SISU_API_URL: "${SISU_API_URL}"
      AALTO_GRADES_FRONTEND_CORS_ORIGIN: "http://frontend:80"
    networks:
      - local

  database:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    networks:
      - local
      
networks:
  local:
    driver: bridge
