# SPDX-FileCopyrightText: 2023 The Aalto Grades Developers
#
# SPDX-License-Identifier: MIT

# This is a Docker Compose configuration for deploying Aalto Grades to a
# virtual machine from the main branch. Requires correct setup work to be done
# on the VM. Documentation for deployment is available in the aalto wiki.
---
version: '3.7'

services:
  reverse-proxy:
    image: nginx:1.27-alpine
    restart: always
    container_name: reverse-proxy
    ports:
      - 443:443
      - 80:80
    volumes:
      - ${CERT_FILE}:/etc/ssl/certs/aalto-grades.cs.aalto.fi.crt
      - ${CERT_KEY_FILE}:/etc/ssl/private/aalto-grades.cs.aalto.fi.key
      # - ./reverse-proxy.conf:/etc/nginx/conf.d/default.conf
      - ./reverse-proxy.conf:/etc/nginx/templates/nginx.conf.template
    environment:
      - NGINX_ENVSUBST_OUTPUT_DIR: /etc/nginx # If necessary otherwise delete it
      - SERVER_NAME: '${SERVER_NAME}'
    networks:
      - local

  frontend:
    extends:
      file: ./common-services.yaml
      service: frontend-minimum
    image: ghcr.io/aalto-grades/aalto-grades-frontend:main
    container_name: frontend-server

  backend:
    extends:
      file: ./common-services.yaml
      service: backend-minimum
    image: ghcr.io/aalto-grades/aalto-grades-backend:main
    container_name: backend-server
    environment:
      AALTO_GRADES_BACKEND_PORT: '${AALTO_GRADES_BACKEND_PORT}'
      AALTO_GRADES_FRONTEND_CORS_ORIGIN: '${AALTO_GRADES_FRONTEND_CORS_ORIGIN}'
      AALTO_GRADES_JWT_SECRET: '${AALTO_GRADES_JWT_SECRET}'
      APLUS_API_URL: '${APLUS_API_URL}'
      SAML_CALLBACK: '${SAML_CALLBACK}'
      SAML_ENTRYPOINT: '${SAML_ENTRYPOINT}'
      SAML_ISSUER: '${SAML_ISSUER}'
      SAML_METADATA_URL: '${SAML_METADATA_URL}'
      NODE_ENV: 'production'
    volumes:
      - ${SAML_DECRYPTION_PVK_FILE}:/keys/saml-decryption-key.pem
      - ${SAML_PRIVATE_KEY_FILE}:/keys/saml-private-key.pem
      - ${SAML_SP_CERT_FILE}:/keys/saml-sp-cert.pem
    logging:
      driver: syslog
      options:
        syslog-address: 'tcp://localhost:601'
        tag: 'aalto-grades'

  database:
    extends:
      file: ./common-services.yaml
      service: database
    environment:
      PGDATA: '/var/lib/postgresql/data/pgdata'
    volumes:
      - ${POSTGRES_MOUNTDIR}:/var/lib/postgresql/data

networks:
  local:
    driver: bridge
