# SPDX-FileCopyrightText: 2022 The Aalto Grades Developers
#
# SPDX-License-Identifier: MIT

# This is a Docker Compose configuration for executing Aalto Grades normally,
# optionally without the frontend
---

version: "3.7"

services:
  frontend:
    extends:
      file: ./common-services.yaml
      service: frontend-common
    container_name: frontend-server
    ports:
      - 3005:80
    restart: always

  backend:
    extends:
      file: ./common-services.yaml
      service: backend-common
    container_name: backend-server
    ports:
      - 3000:3000
    restart: always

  database:
    extends:
      file: ./common-services.yaml
      service: database

networks:
  local:
    driver: bridge
