# SPDX-FileCopyrightText: 2024 The Ossi Developers
#
# SPDX-License-Identifier: MIT

# This is a Docker Compose configuration for deploying Ossi to a
# virtual machine from the dev branch. Requires correct setup work to be done
# on the VM. Documentation for deployment is available in the aalto wiki.

---
services:
  reverse-proxy:
    extends:
      file: ./docker-compose-from-images.yaml
      service: reverse-proxy
    depends_on:
      - frontend
      - backend

  frontend:
    extends:
      file: ./docker-compose-from-images.yaml
      service: frontend
    image: ghcr.io/aalto-grades/aalto-grades-frontend-dev:dev

  backend:
    extends:
      file: ./docker-compose-from-images.yaml
      service: backend
    environment:
      OTEL_SERVICE_NAME: "ossi-test-backend"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-lgtm:4317"
      OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"
      NODE_OPTIONS: >-
        --require @opentelemetry/auto-instrumentations-node/register
    image: ghcr.io/aalto-grades/aalto-grades-backend-dev:dev

  database:
    extends:
      file: ./docker-compose-from-images.yaml
      service: database

  otel-lgtm:
    extends:
      file: ./docker-compose-from-images.yaml
      service: otel-lgtm
    volumes:
      - "./grafana_volume/data:/data"
    environment:
      - OTEL_RESOURCE_ATTRIBUTES=service.name=otel-lgtm-dev

  watchtower:
    image: containrrr/watchtower
    # run docker compose with flag '--profile test' to run watchtower
    profiles:
      - test
    environment:
      WATCHTOWER_NOTIFICATIONS: email
      WATCHTOWER_NOTIFICATION_EMAIL_FROM: root@aalto-grades-test.cs.aalto.fi
      WATCHTOWER_NOTIFICATION_EMAIL_TO: guido.bordonaro@aalto.fi
      # Using local smtp server of aalto vm
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER: localhost
      WATCHTOWER_NOTIFICATION_EMAIL_DELAY: 2
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER_TLS_SKIP_VERIFY: true
      WATCHTOWER_NOTIFICATIONS_LEVEL: error
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    # To use the local smtp server of aalto vm
    network_mode: host
    command: --interval 3600 --cleanup
