packages:
  - "client"
  - "server"
  - "e2e-tests"
  - "common"
linkWorkspacePackages: true
minimumReleaseAge: 2880
allowBuilds:
  "@parcel/watcher": true
  "@scarf/scarf": false
  "@swc/core": true
  argon2: true
  esbuild: true
  protobufjs: true
  "react-global-modal": true
  unrs-resolver: true
