packages:
  - "client"
  - "server"
  - "e2e-tests"
  - "common"
linkWorkspacePackages: true
syncInjectedDepsAfterScripts:
- build
minimumReleaseAge: 2880
allowBuilds:
  "@parcel/watcher": false
  "@scarf/scarf": false
  "@swc/core": false
  argon2: false
  esbuild: false
  protobufjs: false
  "react-global-modal": true
  unrs-resolver: false
