// SPDX-FileCopyrightText: 2023 The Aalto Grades Developers
//
// SPDX-License-Identifier: MIT

import {StudentGradesTree} from 'aalto-grades-common/types/grades';
import {Status} from 'aalto-grades-common/types';

export const mockGradeFullTree: StudentGradesTree[] = [
  {
    userId: 519,
    studentNumber: '117486',
    credits: 5,
    attainmentId: 1,
    attainmentName: 'name1',
    grades: [
      {
        gradeId: 196181,
        grader: {
          id: 2506,
          name: 'Andy Admin',
        },
        grade: 18,
        status: Status.Pass,
        manual: false,
        exportedToSisu: undefined,
        comment: '',
      },
      {
        gradeId: 196183,
        grader: {
          id: 2506,
          name: 'Andy Admin',
        },
        grade: 18,
        status: Status.Pass,
        manual: false,
        exportedToSisu: undefined,
        comment: '',
      },
      {
        gradeId: 196180,
        grader: {
          id: 2506,
          name: 'Andy Admin',
        },
        grade: 18,
        status: Status.Pass,
        manual: false,
        exportedToSisu: undefined,
        comment: '',
      },
      {
        gradeId: 196182,
        grader: {
          id: 2506,
          name: 'Andy Admin',
        },
        grade: 18,
        status: Status.Pass,
        manual: false,
        exportedToSisu: undefined,
        comment: '',
      },
    ],
    subAttainments: [
      {
        attainmentId: 16,
        attainmentName: 'name16',
        grades: [
          {
            gradeId: 5,
            grader: {
              id: 1,
              name: 'Amanda Germain',
            },
            grade: 0.1,
            status: Status.Pass,
            manual: true,
            exportedToSisu: undefined,
            date: '2022-01-05',
            expiryDate: '2023-04-23',
            comment: '',
          },
        ],
        subAttainments: [],
      },
      {
        attainmentId: 17,
        attainmentName: 'name17',
        grades: [
          {
            gradeId: 6,
            grader: {
              id: 1,
              name: 'Amanda Germain',
            },
            grade: 3,
            status: Status.Pass,
            manual: true,
            exportedToSisu: undefined,
            date: '2022-01-05',
            expiryDate: '2023-04-23',
            comment: '',
          },
        ],
        subAttainments: [],
      },
      {
        attainmentId: 5,
        attainmentName: 'name5',
        grades: [
          {
            gradeId: 3,
            grader: {
              id: 1,
              name: 'Amanda Germain',
            },
            grade: 1.5,
            status: Status.Pass,
            manual: true,
            exportedToSisu: undefined,
            date: '2022-01-05',
            expiryDate: '2023-04-23',
            comment: '',
          },
        ],
        subAttainments: [],
      },
      {
        attainmentId: 9,
        attainmentName: 'name9',
        grades: [
          {
            gradeId: 4,
            grader: {
              id: 1,
              name: 'Amanda Germain',
            },
            grade: 2.2,
            status: Status.Pass,
            manual: true,
            exportedToSisu: undefined,
            date: '2022-01-05',
            expiryDate: '2023-04-23',
            comment: '',
          },
        ],
        subAttainments: [],
      },
      {
        attainmentId: 18,
        attainmentName: 'name18',
        grades: [
          {
            gradeId: 7,
            grader: {
              id: 1,
              name: 'Amanda Germain',
            },
            grade: 2.2,
            status: Status.Pass,
            manual: true,
            exportedToSisu: undefined,
            date: '2022-01-05',
            expiryDate: '2023-04-23',
            comment: '',
          },
        ],
        subAttainments: [],
      },
    ],
  },
  {
    userId: 28,
    studentNumber: '812472',
    credits: 5,
    attainmentId: 1,
    attainmentName: 'name1',
    grades: [
      {
        gradeId: 167,
        grader: {
          id: 2507,
          name: 'aalto tester',
        },
        grade: 3,
        status: Status.Pass,
        manual: true,
        exportedToSisu: undefined,
        date: '2023-12-24',
        comment: '',
      },
      {
        gradeId: 203,
        grader: {
          id: 2508,
          name: 'aalto tester',
        },
        grade: 3,
        status: Status.Pass,
        manual: true,
        exportedToSisu: undefined,
        date: '2023-12-24',
        comment: '',
      },
      {
        gradeId: 239,
        grader: {
          id: 2507,
          name: 'aalto tester',
        },
        grade: 3,
        status: Status.Pass,
        manual: true,
        exportedToSisu: undefined,
        date: '2023-12-24',
        comment: '',
      },
      {
        gradeId: 196083,
        grader: {
          id: 2507,
          name: 'aalto tester',
        },
        grade: 3,
        status: Status.Pass,
        manual: true,
        exportedToSisu: undefined,
        date: '2023-12-24',
        expiryDate: '2024-12-24',
        comment: '',
      },
      {
        gradeId: 196119,
        grader: {
          id: 2507,
          name: 'aalto tester',
        },
        grade: 3,
        status: Status.Pass,
        manual: true,
        exportedToSisu: undefined,
        date: '2023-12-24',
        comment: '',
      },
    ],
    subAttainments: [
      {
        attainmentId: 16,
        attainmentName: 'name16',
        grades: [
          {
            gradeId: 165,
            grader: {
              id: 2507,
              name: 'aalto tester',
            },
            grade: 12,
            status: Status.Pass,
            manual: true,
            exportedToSisu: undefined,
            date: '2023-12-24',
            comment: '',
          },
          {
            gradeId: 201,
            grader: {
              id: 2508,
              name: 'aalto tester',
            },
            grade: 12,
            status: Status.Pass,
            manual: true,
            exportedToSisu: undefined,
            date: '2023-12-24',
            comment: '',
          },
          {
            gradeId: 237,
            grader: {
              id: 2507,
              name: 'aalto tester',
            },
            grade: 12,
            status: Status.Pass,
            manual: true,
            exportedToSisu: undefined,
            date: '2023-12-24',
            comment: '',
          },
          {
            gradeId: 196081,
            grader: {
              id: 2507,
              name: 'aalto tester',
            },
            grade: 12,
            status: Status.Pass,
            manual: true,
            exportedToSisu: undefined,
            date: '2023-12-24',
            expiryDate: '2024-12-24',
            comment: '',
          },
          {
            gradeId: 196117,
            grader: {
              id: 2507,
              name: 'aalto tester',
            },
            grade: 12.3,
            status: Status.Pass,
            manual: true,
            exportedToSisu: undefined,
            date: '2023-12-24',
            comment: '',
          },
        ],
        subAttainments: [],
      },
      {
        attainmentId: 17,
        attainmentName: 'name17',
        grades: [
          {
            gradeId: 166,
            grader: {
              id: 2507,
              name: 'aalto tester',
            },
            grade: 32,
            status: Status.Pass,
            manual: true,
            exportedToSisu: undefined,
            date: '2023-12-24',
            comment: '',
          },
          {
            gradeId: 202,
            grader: {
              id: 2508,
              name: 'aalto tester',
            },
            grade: 32,
            status: Status.Pass,
            manual: true,
            exportedToSisu: undefined,
            date: '2023-12-24',
            comment: '',
          },
          {
            gradeId: 238,
            grader: {
              id: 2507,
              name: 'aalto tester',
            },
            grade: 32,
            status: Status.Pass,
            manual: true,
            exportedToSisu: undefined,
            date: '2023-12-24',
            comment: '',
          },
          {
            gradeId: 196082,
            grader: {
              id: 2507,
              name: 'aalto tester',
            },
            grade: 32,
            status: Status.Pass,
            manual: true,
            exportedToSisu: undefined,
            date: '2023-12-24',
            expiryDate: '2024-12-24',
            comment: '',
          },
          {
            gradeId: 196118,
            grader: {
              id: 2507,
              name: 'aalto tester',
            },
            grade: 32,
            status: Status.Pass,
            manual: true,
            exportedToSisu: undefined,
            date: '2023-12-24',
            comment: '',
          },
        ],
        subAttainments: [],
      },
      {
        attainmentId: 5,
        attainmentName: 'name5',
        grades: [
          {
            gradeId: 168,
            grader: {
              id: 2507,
              name: 'aalto tester',
            },
            grade: 5,
            status: Status.Pass,
            manual: true,
            exportedToSisu: undefined,
            date: '2023-12-24',
            comment: '',
          },
          {
            gradeId: 204,
            grader: {
              id: 2508,
              name: 'aalto tester',
            },
            grade: 5,
            status: Status.Pass,
            manual: true,
            exportedToSisu: undefined,
            date: '2023-12-24',
            comment: '',
          },
          {
            gradeId: 240,
            grader: {
              id: 2507,
              name: 'aalto tester',
            },
            grade: 5,
            status: Status.Pass,
            manual: true,
            exportedToSisu: undefined,
            date: '2023-12-24',
            comment: '',
          },
          {
            gradeId: 196084,
            grader: {
              id: 2507,
              name: 'aalto tester',
            },
            grade: 5,
            status: Status.Pass,
            manual: true,
            exportedToSisu: undefined,
            date: '2023-12-24',
            expiryDate: '2024-12-24',
            comment: '',
          },
          {
            gradeId: 196120,
            grader: {
              id: 2507,
              name: 'aalto tester',
            },
            grade: 5,
            status: Status.Pass,
            manual: true,
            exportedToSisu: undefined,
            date: '2023-12-24',
            comment: '',
          },
        ],
        subAttainments: [],
      },
      {
        attainmentId: 9,
        attainmentName: 'name9',
        grades: [
          {
            gradeId: 169,
            grader: {
              id: 2507,
              name: 'aalto tester',
            },
            grade: 2,
            status: Status.Pass,
            manual: true,
            exportedToSisu: undefined,
            date: '2023-12-24',
            comment: '',
          },
          {
            gradeId: 205,
            grader: {
              id: 2508,
              name: 'aalto tester',
            },
            grade: 2,
            status: Status.Pass,
            manual: true,
            exportedToSisu: undefined,
            date: '2023-12-24',
            comment: '',
          },
          {
            gradeId: 241,
            grader: {
              id: 2507,
              name: 'aalto tester',
            },
            grade: 2,
            status: Status.Pass,
            manual: true,
            exportedToSisu: undefined,
            date: '2023-12-24',
            comment: '',
          },
          {
            gradeId: 196085,
            grader: {
              id: 2507,
              name: 'aalto tester',
            },
            grade: 2,
            status: Status.Pass,
            manual: true,
            exportedToSisu: undefined,
            date: '2023-12-24',
            expiryDate: '2024-12-24',
            comment: '',
          },
          {
            gradeId: 196121,
            grader: {
              id: 2507,
              name: 'aalto tester',
            },
            grade: 2,
            status: Status.Pass,
            manual: true,
            exportedToSisu: undefined,
            date: '2023-12-24',
            comment: '',
          },
        ],
        subAttainments: [],
      },
      {
        attainmentId: 18,
        attainmentName: 'name18',
        grades: [
          {
            gradeId: 170,
            grader: {
              id: 2507,
              name: 'aalto tester',
            },
            grade: 7,
            status: Status.Pass,
            manual: true,
            exportedToSisu: undefined,
            date: '2023-12-24',
            comment: '',
          },
          {
            gradeId: 206,
            grader: {
              id: 2508,
              name: 'aalto tester',
            },
            grade: 7,
            status: Status.Pass,
            manual: true,
            exportedToSisu: undefined,
            date: '2023-12-24',
            comment: '',
          },
          {
            gradeId: 242,
            grader: {
              id: 2507,
              name: 'aalto tester',
            },
            grade: 7,
            status: Status.Pass,
            manual: true,
            exportedToSisu: undefined,
            date: '2023-12-24',
            comment: '',
          },
          {
            gradeId: 196086,
            grader: {
              id: 2507,
              name: 'aalto tester',
            },
            grade: 7,
            status: Status.Pass,
            manual: true,
            exportedToSisu: undefined,
            date: '2023-12-24',
            expiryDate: '2024-12-24',
            comment: '',
          },
          {
            gradeId: 196122,
            grader: {
              id: 2507,
              name: 'aalto tester',
            },
            grade: 7,
            status: Status.Pass,
            manual: true,
            exportedToSisu: undefined,
            date: '2023-12-24',
            comment: '',
          },
        ],
        subAttainments: [],
      },
    ],
  },
];
