# SPDX-FileCopyrightText: 2022 The Aalto Grades Developers
#
# SPDX-License-Identifier: MIT

FROM node:18-alpine

WORKDIR /app
RUN mkdir common server && chown node:node server

# Install packages first to make following builds faster
WORKDIR /app/server
COPY server/package.json server/package-lock.json ./
RUN npm ci

# Copy common first
WORKDIR /app
COPY common/types common/types

# Copy only necessary server files
WORKDIR /app/server
COPY server/tsconfig.json server/.sequelizerc server/jest.config.js ./
COPY server/mock-data ./mock-data
COPY server/test ./test
COPY server/src ./src

USER node
RUN npm run build

EXPOSE 3000
CMD ["/bin/sh", "-c", "\
    npm run migration:up && \
    npm run seed:up && \
    npm test"]
