# SPDX-FileCopyrightText: 2023 The Aalto Grades Developers
#
# SPDX-License-Identifier: MIT

# This is a Docker Compose configuration for running the backend
---

version: "3.7"

services:
  backend:
    extends:
      file: ../common-services.yaml
      service: backend-common
    container_name: "backend-server"
    ports:
      - 3000:3000

  database:
    extends:
      file: ../common-services.yaml
      service: database
    ports:
      - 5432:5432

  pgadmin:
    extends:
      file: ../common-services.yaml
      service: pgadmin
    depends_on:
      - database
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    profiles:
      - development
    volumes:
      - ./pgAdminSetup.json:/pgadmin4/servers.json
      - ./pgAdminpass:/pgpass

networks:
  local:
    driver: bridge
