# SPDX-FileCopyrightText: 2023 The Aalto Grades Developers
#
# SPDX-License-Identifier: MIT

# This is a Docker Compose configuration for running the backend unit tests
---

version: "3.7"

services:
  backend:
    extends:
      file: ../common-services.yaml
      service: backend-common-test
    container_name: "backend-server-test"

  database:
    extends:
      file: ../common-services.yaml
      service: database

networks:
  local:
    driver: bridge
