# SPDX-FileCopyrightText: 2023 The Aalto Grades Developers
#
# SPDX-License-Identifier: MIT

# This is a Docker Compose configuration for running backend unit tests

version: "3.7"

services:
  backend:
    extends:
      file: ../common-services.yaml
      service: backend
    container_name: backend-server-test
    environment:
      SERVER_RUN_TESTS: 1
      
  database:
    extends:
      file: ../common-services.yaml
      service: database

networks:
  local:
    driver: bridge
