# SPDX-FileCopyrightText: 2023 The Aalto Grades Developers
#
# SPDX-License-Identifier: MIT

# This is a Docker Compose configuration for running backend unit tests or development

version: "3.7"

services:
  backend:
    extends:
      file: ../common-services.yaml
      service: backend
    container_name: "backend-server-${NODE_ENV}"
    environment:
      NODE_ENV: "${NODE_ENV}"
      
  database:
    extends:
      file: ../common-services.yaml
      service: database

  pgadmin:
    image: dpage/pgadmin4:latest
    depends_on:
      - database
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    networks:
      - local
    profiles:
      - development
    volumes:
      - ./pgAdminSetup.json:/pgadmin4/servers.json
      - ./pgAdminpass:/pgpass

networks:
  local:
    driver: bridge
