# SPDX-FileCopyrightText: 2023 The Aalto Grades Developers
#
# SPDX-License-Identifier: MIT

# This is a Docker Compose configuration for running the backend
# Or just the database by running `docker compose up database`

---
services:
  backend:
    build:
      context: ..
      dockerfile: ./server/dockerfiles/Dockerfile
    container_name: aalto-grades-backend-dev-backend-only
    ports:
      - 3000:3000
    environment:
      POSTGRES_URL: 'database'
      POSTGRES_USER: 'postgres'
      POSTGRES_DATABASE: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
    depends_on:
      - database

  database:
    image: postgres:15
    container_name: aalto-grades-database-dev-backend-only
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: 'postgres'

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: aalto-grades-pgadmin-dev-backend-only
    ports:
      - '5050:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@aalto.fi
      PGADMIN_DEFAULT_PASSWORD: password
    profiles:
      - development
    volumes:
      - ./pgAdminSetup.json:/pgadmin4/servers.json
      - ./pgAdminpass:/pgpass
    depends_on:
      - database
