# SPDX-FileCopyrightText: 2023 The Aalto Grades Developers
#
# SPDX-License-Identifier: MIT

# This is a Docker Compose configuration for executing Cypress end-to-end tests
---

version: "3.7"

services:
  frontend:
    extends:
      file: ../common-services.yaml
      service: frontend
    container_name: frontend-server-cypress
    environment:
      REACT_APP_BACKEND_URL: "http://backend"
      REACT_APP_BACKEND_PORT: "3000"

  backend:
    extends:
      file: ../common-services.yaml
      service: backend
    container_name: backend-server-cypress
    environment:
      AALTO_GRADES_FRONTEND_CORS_ORIGIN: "http://frontend:3005"

  database:
    extends:
      file: ../common-services.yaml
      service: database

  cypress:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      LOCALHOST_URL: "http://frontend:3005"
    volumes:
      - ./cypress:/app/cypress
    depends_on:
      - backend
      - frontend
    networks:
      - local

networks:
  local:
    driver: bridge
