// SPDX-FileCopyrightText: 2023 The Aalto Grades Developers
//
// SPDX-License-Identifier: MIT

const mockAssignmentsClient = [
  { id: 1,
    name: 'Exercises',
    category: 'Other',
    date: new Date(2023, 9, 1),
    expiryDate: new Date(2024, 8, 14), 
    formulaId: 1,
    subAssignments: [ 
      { id: 11, 
        name: '4 mandatory exercises',
        category: 'Other',
        date: new Date(2023, 9, 1), 
        expiryDate: new Date(2024, 8, 14), 
        formulaId: 1,
        subAssignments: [
          { id: 111, 
            name: 'Exercise 1',
            category: 'Other',
            date: new Date(2023, 9, 1), 
            expiryDate: new Date(2024, 8, 14),
            subAssignments: [],
          }, 
          { id: 112, 
            name: 'Exercise 2',
            category: 'Other',
            date: new Date(2023, 9, 1), 
            expiryDate: new Date(2024, 8, 14),
            subAssignments: [],
          }, 
          { id: 113, 
            name: 'Exercise 3',
            category: 'Other',
            date: new Date(2023, 9, 1), 
            expiryDate: new Date(2024, 8, 14), 
            formulaId: 1,
            subAssignments: [
              { id: 1131, 
                name: 'Exercise 3.1',
                category: 'Other',
                date: new Date(2023, 9, 1), 
                expiryDate: new Date(2024, 8, 14),
                subAssignments: [],
              }, 
              { id: 1132,
                name: 'Exercise 3.2',
                category: 'Other',
                date: new Date(2023, 9, 1), 
                expiryDate: new Date(2024, 8, 14), 
                subAssignments: [],
              }
            ] 
          }, 
          { id: 114, 
            name: 'Exercise 4',
            category: 'Other',
            date: new Date(2023, 9, 1), 
            expiryDate: new Date(2024, 8, 14),
            subAssignments: [],
          }
        ] 
      },
      { id: 12, 
        name: '3 optional exercises', 
        category: 'Other',
        date: new Date(2023, 9, 1), 
        expiryDate: new Date(2024, 8, 14), 
        formulaId: 1,
        subAssignments: [
          { id: 121, 
            name: 'Exercise 5',
            category: 'Other',
            date: new Date(2023, 9, 1), 
            expiryDate: new Date(2024, 8, 14),
            subAssignments: [],
          }, 
          { id: 122, 
            name: 'Exercise 6',
            category: 'Other',
            date: new Date(2023, 9, 1), 
            expiryDate: new Date(2024, 8, 14),
            subAssignments: [],
          }, 
          { id: 123, 
            name: 'Exercise 7',
            category: 'Other',
            date: new Date(2023, 9, 1), 
            expiryDate: new Date(2024, 8, 14),
            subAssignments: [],
          },
        ] 
      }
    ]
  },
  { id: 2,
    name: 'Project',
    category: 'Project',
    date: new Date(2023, 9, 1), 
    expiryDate: new Date(2024, 8, 14),
    subAssignments: [],
  },
  { id: 3,
    name: 'Exam',
    category: 'Exam',
    date: new Date(2023, 9, 1), 
    expiryDate: new Date(2024, 8, 14),
    subAssignments: [],
  }
];

export default mockAssignmentsClient;