-- SPDX-FileCopyrightText: 2022 The Aalto Grades Developers
--
-- SPDX-License-Identifier: MIT

INSERT INTO public.course_role (user_id, course_instance_id, role, created_at, updated_ad) VALUES
(1, 1, 'TEACHERINCHARGE', NOW(), NOW()),
(2, 2, 'TEACHERINCHARGE', NOW(), NOW()),
(3, 3, 'TEACHERINCHARGE', NOW(), NOW()),
(3, 4, 'TEACHERINCHARGE', NOW(), NOW()),
(3, 5, 'TEACHERINCHARGE', NOW(), NOW()),
(3, 6, 'TEACHERINCHARGE', NOW(), NOW()),
(4, 7, 'TEACHERINCHARGE', NOW(), NOW()),
(7, 8, 'TEACHERINCHARGE', NOW(), NOW()),
(6, 9, 'TEACHERINCHARGE', NOW(), NOW()),
(8, 10, 'TEACHERINCHARGE', NOW(), NOW()),
(2, 11, 'TEACHERINCHARGE', NOW(), NOW()),
(9, 12, 'TEACHERINCHARGE', NOW(), NOW()),
(10, 13, 'TEACHERINCHARGE', NOW(), NOW()),
(8, 14, 'TEACHERINCHARGE', NOW(), NOW()),
(6, 15, 'TEACHERINCHARGE', NOW(), NOW()),
(4, 16, 'TEACHERINCHARGE', NOW(), NOW()),
(7, 17, 'TEACHERINCHARGE', NOW(), NOW()),
(6, 18, 'TEACHERINCHARGE', NOW(), NOW()),
(8, 19, 'TEACHERINCHARGE', NOW(), NOW()),
(2, 20, 'TEACHERINCHARGE', NOW(), NOW()),
(9, 21, 'TEACHERINCHARGE', NOW(), NOW()),
