# SPDX-FileCopyrightText: 2024 The Aalto Grades Developers
#
# SPDX-License-Identifier: MIT
---
name: Image Creation
on: # yamllint disable-line rule:truthy
  workflow_call:
    inputs:
      registry:
        required: true
        type: string
      client_image_name:
        required: true
        type: string
      server_image_name:
        required: true
        type: string

jobs:
  build_and_publish_client_and_server:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ inputs.registry }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for client
        id: meta_front
        uses: docker/metadata-action@v5
        with:
          images: ${{ inputs.registry }}/${{ inputs.client_image_name }}

      - name: Extract metadata for server
        id: meta_back
        uses: docker/metadata-action@v5
        with:
          images: ${{ inputs.registry }}/${{ inputs.server_image_name }}

      - name: Build and push client Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: client/Dockerfile.prod
          push: true
          tags: ${{ steps.meta_front.outputs.tags }}
          labels: ${{ steps.meta_front.outputs.labels }}

      - name: Build and push server Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: server/Dockerfile.prod
          push: true
          tags: ${{ steps.meta_back.outputs.tags }}
          labels: ${{ steps.meta_back.outputs.labels }}
