# SPDX-FileCopyrightText: 2024 The Ossi Developers
#
# SPDX-License-Identifier: MIT
---
name: Build E2E Images
on:
  workflow_call:
    outputs:
      docker-images-cache-key:
        description: Cache key for built Docker images
        value: ${{ jobs.build-images.outputs.docker-images-cache-key }}

jobs:
  build-images:
    name: Build Docker images for E2E tests
    runs-on: ubuntu-latest
    outputs:
      docker-images-cache-key: ${{ steps.generate-cache-key.outputs.key }}
    steps:
      - uses: actions/checkout@v4

      - name: Generate Docker images cache key
        id: generate-cache-key
        run: |
          # Create a cache key based on relevant files
          echo "key=docker-images-${{ runner.os }}-${{ hashFiles('**/Dockerfile*', '**/package*.json', 'docker-compose*.yaml') }}-${{ github.sha }}" >> $GITHUB_OUTPUT

      - name: Check for cached Docker images
        id: docker-images-cache
        uses: actions/cache@v3
        with:
          path: /tmp/docker-images
          key: ${{ steps.generate-cache-key.outputs.key }}

      - name: Install NPM dependencies
        if: steps.docker-images-cache.outputs.cache-hit != 'true'
        run: npm ci

      - name: Clean up existing Docker containers
        if: steps.docker-images-cache.outputs.cache-hit != 'true'
        run: docker compose down --volumes --remove-orphans

      - name: Build Docker images
        if: steps.docker-images-cache.outputs.cache-hit != 'true'
        run: docker compose build --no-cache

      - name: Save Docker images to cache
        if: steps.docker-images-cache.outputs.cache-hit != 'true'
        run: |
          mkdir -p /tmp/docker-images

          echo "=== All available Docker images ==="
          docker images

          echo "=== Getting ALL image IDs ==="
          # Just get all image IDs and save them all
          IMAGE_IDS=$(docker images --format "{{.ID}}" | grep -v "^IMAGE" | head -20)

          echo "Image IDs to save:"
          echo "$IMAGE_IDS"

          if [ -n "$IMAGE_IDS" ]; then
            echo "Saving all images..."
            docker save $IMAGE_IDS -o /tmp/docker-images/images.tar
            echo "✅ All images saved successfully"
            ls -lh /tmp/docker-images/images.tar
          else
            echo "❌ No images found"
            tar -cf /tmp/docker-images/images.tar --files-from /dev/null
          fi
