# SPDX-FileCopyrightText: 2024 The Ossi Developers
#
# SPDX-License-Identifier: MIT
---
name: Build E2E Images
on:
  workflow_call:
    outputs:
      docker-images-cache-key:
        description: Cache key for built Docker images
        value: ${{ jobs.build-images.outputs.docker-images-cache-key }}

jobs:
  build-images:
    name: Build Docker images for E2E tests
    runs-on: ubuntu-latest
    outputs:
      docker-images-cache-key: ${{ steps.generate-cache-key.outputs.key }}
    steps:
      - uses: actions/checkout@v4

      - name: Generate Docker images cache key
        id: generate-cache-key
        run: |
          # Create a cache key based on relevant files
          echo "key=docker-images-${{ runner.os }}-${{ hashFiles('**/Dockerfile*', '**/package*.json', 'docker-compose*.yaml') }}-${{ github.sha }}" >> $GITHUB_OUTPUT

      - name: Check for cached Docker images
        id: docker-images-cache
        uses: actions/cache@v3
        with:
          path: /tmp/docker-images
          key: ${{ steps.generate-cache-key.outputs.key }}

      - name: Install NPM dependencies
        if: steps.docker-images-cache.outputs.cache-hit != 'true'
        run: npm ci

      - name: Clean up existing Docker containers
        if: steps.docker-images-cache.outputs.cache-hit != 'true'
        run: docker compose down --volumes --remove-orphans

      - name: Build Docker images
        if: steps.docker-images-cache.outputs.cache-hit != 'true'
        run: docker compose build --no-cache

      - name: Save Docker images to cache
        if: steps.docker-images-cache.outputs.cache-hit != 'true'
        run: |
          mkdir -p /tmp/docker-images
          # List all docker images and filter for our project
          echo "Available Docker images:"
          docker images

          # Get images that were built by docker compose (exclude base images)
          IMAGES=$(docker images --format "table {{.Repository}}:{{.Tag}}" | grep -E "aalto-grades|frontend|backend" | grep -v "nginx\|postgres" | tail -n +2 | tr '\n' ' ')

          if [ -z "$IMAGES" ]; then
            # Fallback: try to get images by project name
            PROJECT_NAME=$(basename $(pwd) | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9]//g')
            IMAGES=$(docker images --format "table {{.Repository}}:{{.Tag}}" | grep "$PROJECT_NAME" | grep -v "nginx\|postgres" | tail -n +2 | tr '\n' ' ')
          fi

          echo "Images to save: $IMAGES"

          if [ -n "$IMAGES" ]; then
            docker save $IMAGES -o /tmp/docker-images/images.tar
            echo "Images saved successfully"
          else
            echo "No custom images found to save, creating empty tar"
            tar -cf /tmp/docker-images/images.tar --files-from /dev/null
          fi
