---

name: Check Translation Keys

on:
  push:
    paths:
      - 'client/public/locales/**' # Run only when updates to the locales i.e., client translations

jobs:
  check-translation-keys:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Check JSON translations keys consistency
        run: |
          python .github/scripts/check_translation_keys.py
