# SPDX-FileCopyrightText: 2024 The Ossi Developers
#
# SPDX-License-Identifier: MIT
---
name: Dev Push Workflow
run-name: Dev push workflow (${{ github.actor }})

on:
  push:
    branches:
      - dev

jobs:
  run_e2e_tests:
    uses: ./.github/workflows/e2e-tests.yaml

  server_tests:
    uses: ./.github/workflows/server-tests.yaml

  lint_project:
    uses: ./.github/workflows/lint-project.yaml
