# SPDX-FileCopyrightText: 2024 The Ossi Developers
#
# SPDX-License-Identifier: MIT
---
name:  "[main] Push Workflow"
run-name: Main push workflow (${{ github.actor }})

on:
  push:
    branches:
      - main

jobs:
  run_e2e_tests:
    uses: ./.github/workflows/e2e-tests.yaml

  server_tests:
    uses: ./.github/workflows/server-tests.yaml

  lint_project:
    uses: ./.github/workflows/lint-project.yaml
