# SPDX-FileCopyrightText: 2024 The Aalto Grades Developers
#
# SPDX-License-Identifier: MIT
---
name: Dev Push Workflow
run-name: Dev push workflow (${{ github.actor }})

on: # yamllint disable-line rule:truthy
  push:
    branches:
      - dev

jobs:
  run_e2e_tests:
    uses: aalto-grades/aalto-grades/.github/workflows/shared/e2e-tests.yaml@improve-workflows

  server_tests:
    uses: aalto-grades/aalto-grades/.github/workflows/shared/server-tests.yaml@improve-workflows

  lint_project:
    uses: aalto-grades/aalto-grades/.github/workflows/shared/lint-project.yaml@improve-workflows
