# SPDX-FileCopyrightText: 2024 The Ossi Developers
#
# SPDX-License-Identifier: MIT
---
name: Dev Image Creation Workflow
run-name: Dev image creation (${{ github.actor }})

on:
  push:
    branches:
      - dev

jobs:
  build_and_publish:
    uses: ./.github/workflows/build-and-publish.yaml
    with:

      registry: ghcr.io
      client_image_name: aalto-grades/aalto-grades-frontend-dev
      server_image_name: aalto-grades/aalto-grades-backend-dev
