# SPDX-FileCopyrightText: 2024 The Ossi Developers
#
# SPDX-License-Identifier: MIT
---
name: E2E Tests - Chrome
on:
  workflow_call:
    inputs:
      docker-images-cache-key:
        description: Cache key for pre-built Docker images from build step
        required: true
        type: string

jobs:
  e2e-chrome:
    name: Run e2e tests with Chrome
    runs-on: ubuntu-latest
    env:
      LOCALHOST_URL: http://localhost:8080
      DOCKER_IMAGES_PATH: /tmp/docker-images
      DOCKER_IMAGES_TAR: /tmp/docker-images/images.tar
    defaults:
      run:
        working-directory: ./e2e-tests
    steps:
      - uses: actions/checkout@v4

      - name: Restore pre-built Docker images
        id: docker-images-cache
        uses: actions/cache/restore@v3
        with:
          path: ${{ env.DOCKER_IMAGES_PATH }}
          key: ${{ inputs.docker-images-cache-key }}
          fail-on-cache-miss: true

      - name: Load Docker images from cache
        run: |
          echo "Loading pre-built Docker images..."
          docker load -i ${{ env.DOCKER_IMAGES_TAR }}
          echo "Docker images loaded successfully"
          docker images
        working-directory: ./

      - name: Setup Playwright browser cache
        id: playwright-browser-cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-browsers-${{ hashFiles('**/package-lock.json') }}

      - uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install NPM dependencies
        working-directory: ./
        run: npm ci

      - name: Start application services
        working-directory: ./
        run: docker compose up -d

      - name: Install Chrome browser for Playwright
        if: steps.playwright-browser-cache.outputs.cache-hit != 'true'
        run: npx playwright install chromium --with-deps

      - name: Wait for application to be ready
        run: |
          url="${{ env.LOCALHOST_URL }}/login"
          echo "Waiting for application at ${url} to become available..."
          timeout=300
          elapsed=0
          while [ $elapsed -lt $timeout ]; do
            if curl -s -o /dev/null -w "%{http_code}" "${url}" | grep -q "200"; then
              echo "Application is ready after ${elapsed} seconds"
              sleep 10  # Additional grace period
              exit 0
            fi
            echo "Still waiting... (${elapsed}s/${timeout}s)"
            sleep 5
            elapsed=$((elapsed + 5))
          done
          echo "Timeout waiting for application to be ready"
          exit 1
        working-directory: ./

      - name: Clean up previous test artifacts
        run: |
          rm -rf ./blob-reporter ./playwright-report ./blob-report
          mkdir -p ./blob-reporter

      - name: Run Chrome E2E tests
        run: |
          npx playwright test --project chromium --reporter=list,blob
          # Move Chrome-specific report if it exists
          if [ -f ./blob-report/report-chromium.zip ]; then
            mv ./blob-report/report-chromium.zip ./blob-reporter/chrome-report.zip
          fi

      - name: Generate HTML test report
        if: always()
        run: npx playwright merge-reports --reporter=html ./blob-reporter

      - name: Upload HTML test report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: chrome-html-test-report
          path: e2e-tests/playwright-report/
          retention-days: 7

      - name: Upload blob test report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: chrome-blob-test-report
          path: e2e-tests/blob-reporter/
          retention-days: 7
