# SPDX-FileCopyrightText: 2024 The Ossi Developers
#
# SPDX-License-Identifier: MIT
---
name: End-to-end Tests
on: # yamllint disable-line rule:truthy
  workflow_call:

jobs:
  e2e-tests:
    name: Run e2e tests (parallel)
    uses: ./.github/workflows/e2e-parallel.yaml
