# SPDX-FileCopyrightText: 2024 The Ossi Developers
#
# SPDX-License-Identifier: MIT
---
name: End-to-end Tests
on: # yamllint disable-line rule:truthy
  workflow_call:

jobs:
  e2e-tests:
    name: Run e2e tests
    runs-on: ubuntu-latest
    env:
      LOCALHOST_URL: http://localhost:8080
    defaults:
      run:
        working-directory: ./e2e-tests
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v3
        id: playwright-cache
        with:
          path: |
            ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ hashFiles('**/package-lock.json') }}
      - uses: actions/setup-node@v4
        with:
          node-version: 24
      - name: Install dependencies
        run: npm ci
      - name: Docker compose down
        working-directory: ./
        run: docker compose down --volumes --remove-orphans
      - name: Docker compose build
        working-directory: ./
        run: docker compose build --no-cache
      - name: Run app
        working-directory: ./
        run: docker compose up -d
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
        if: steps.playwright-cache.outputs.cache-hit != 'true'
      - name: Run Playwright tests
        run: ./wait-and-run-tests.sh
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: e2e-tests/playwright-report/
          retention-days: 1
