# SPDX-FileCopyrightText: 2024 The Ossi Developers
#
# SPDX-License-Identifier: MIT
---
name: Lint Project
on: # yamllint disable-line rule:truthy
  workflow_call:

jobs:
  lint_code:
    name: Lint project code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install linter packages
        run: npm ci
      - name: Install client packages
        run: npm --prefix ./client ci
      - name: Install server packages
        run: npm --prefix ./server ci
      - name: Install e2e-tests packages
        run: npm --prefix ./e2e-tests ci
      - name: Install common packages
        run: npm --prefix ./common ci
      - name: Run linter
        run: npm run lint

  lint_yaml_files:
    name: Lint project YAML files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install yamllint
        run: pip install yamllint
      - name: Lint YAML files
        run: yamllint .

  reuse_lint:
    name: Check REUSE compliance
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: fsfe/reuse-action@v4
