# SPDX-FileCopyrightText: 2024 The Aalto Grades Developers
#
# SPDX-License-Identifier: MIT
---
name: Main Image Creation Workflow
run-name: Main image creation (${{ github.actor }})

on: # yamllint disable-line rule:truthy
  push:
    branches:
      - main

jobs:
  build_and_publish:
    uses: ./.github/workflows/build-and-publish.yaml
    with:
      registry: ghcr.io
      client_image_name: aalto-grades/aalto-grades-frontend
      server_image_name: aalto-grades/aalto-grades-backend
