# SPDX-FileCopyrightText: 2022 The Aalto Grades Developers
#
# SPDX-License-Identifier: MIT
---
name: End-to-end tests
on: # yamllint disable-line rule:truthy
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - dev
jobs:
  test-e2e:
    name: e2e test
    runs-on: ubuntu-latest
    env:
      LOCALHOST_URL: http://localhost:8080
      POSTGRES_PASSWORD: postgres
    defaults:
      run:
        working-directory: ./e2e-tests
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Docker compose down
        working-directory: ./
        run: docker compose down --volumes --remove-orphans
      - name: Docker compose build
        working-directory: ./
        run: docker compose build --no-cache
      - name: Run app
        working-directory: ./
        run: docker compose up -d
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: ./wait-and-run-tests.sh
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: e2e-tests/playwright-report/
          retention-days: 1
