# SPDX-FileCopyrightText: 2023 The Aalto Grades Developers
#
# SPDX-License-Identifier: MIT
---
name: Pull Request Workflow
run-name: ${{ github.head_ref }} pull request (${{ github.actor }})

on: # yamllint disable-line rule:truthy
  pull_request:
    branches:
      - main
      - dev

jobs:
  run_e2e_tests:
    uses: aalto-grades/aalto-grades/.github/workflows/e2e-tests.yaml@improve-workflows

  server_tests:
    uses: aalto-grades/aalto-grades/.github/workflows/server-tests.yaml@improve-workflows

  lint_project:
    uses: aalto-grades/aalto-grades/.github/workflows/lint-project.yaml@improve-workflows
