# SPDX-FileCopyrightText: 2022 The Aalto Grades Developers
#
# SPDX-License-Identifier: MIT

name: PR Workflow
run-name: ${{ github.actor }} pull request
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test_and_lint_client:
    name: Test and lint client
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test
      - name: Run linter
        run: npm run lint

  test_and_lint_server:
    name: Test and lint server
    runs-on: ubuntu-latest
    env:
      POSTGRES_PASSWORD: postgres
      NODE_ENV: test
      SERVER_SKIP_NPM_CI: 1
    defaults:
      run:
        working-directory: ./server
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: docker-compose up --abort-on-container-exit --exit-code-from backend
      - name: Run linter
        run: npm run lint

  reuse_lint:
    name: Check REUSE compliance
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: fsfe/reuse-action@v1

  # run_end_to_end_tests:
    # name: Run Robot Framework end-to-end tests
    # runs-on: ubuntu-latest
    # env:
      # POSTGRES_PASSWORD: postgres
    # defaults:
      # run:
        # working-directory: ./robot-tests
    # steps:
      # - uses: actions/checkout@v3
      # - name: Set permissions
      #   run: chmod -R 777 .
      # - name: Run tests
        # run: docker-compose up --abort-on-container-exit --exit-code-from robot
