# SPDX-FileCopyrightText: 2023 The Aalto Grades Developers
#
# SPDX-License-Identifier: MIT
---
name: PR Workflow
run-name: ${{ github.actor }} pull request

on: # yamllint disable-line rule:truthy
  pull_request:
    branches:
      - main
      - dev

jobs:
  # Commented out temporarily
  # run_e2e_tests:
  #   uses: aalto-grades/aalto-grades/.github/workflows/e2e-tests.yaml@improve-workflows

  server_tests:
    uses: aalto-grades/aalto-grades/.github/workflows/server-tests.yaml@improve-workflows

  lint_project:
    uses: aalto-grades/aalto-grades/.github/workflows/lint-project.yaml@improve-workflows

  # test_and_lint_client:
  #   name: Test and lint client
  #   runs-on: ubuntu-latest
  #   defaults:
  #     run:
  #       working-directory: ./client
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: actions/setup-node@v4
  #       with:
  #         node-version: 20
  #     - name: Install dependencies
  #       run: npm ci
  #     - name: Install common dependencies
  #       run: npm --prefix ../common ci
  #     - name: Install linter dependencies
  #       run: npm --prefix .. ci
  #     - name: Run linter
  #       run: npm run lint

  # test_and_lint_server:
  #   name: Test and lint server
  #   runs-on: self-hosted
  #   env:
  #     POSTGRES_PASSWORD: postgres
  #     NODE_ENV: test
  #   defaults:
  #     run:
  #       working-directory: ./server
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: actions/setup-node@v4
  #       with:
  #         node-version: 20
  #     - name: Docker compose down
  #       run: docker-compose -f docker-compose-test.yaml down --volumes --remove-orphans
  #     - name: Docker compose build
  #       run: docker-compose -f docker-compose-test.yaml build --no-cache
  #     - name: Run tests
  #       run: >
  #         set -o pipefail &&
  #         docker-compose -f docker-compose-test.yaml up
  #         --abort-on-container-exit --exit-code-from backend
  #         2>&1 | sed '/database_1/d; s/^[^|]*[^ ]* //'
  #     - name: Install dependencies
  #       run: npm ci
  #     - name: Install common dependencies
  #       run: npm --prefix ../common ci
  #     - name: Install linter dependencies
  #       run: npm --prefix .. ci
  #     - name: Run linter
  #       run: npm run lint

  # lint_common:
  #   name: Lint common
  #   runs-on: ubuntu-latest
  #   defaults:
  #     run:
  #       working-directory: ./common
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: actions/setup-node@v4
  #       with:
  #         node-version: 20
  #     - name: Install dependencies
  #       run: npm ci
  #     - name: Install linter dependencies
  #       run: npm --prefix .. ci
  #     - name: Run linter
  #       run: npm run lint

  # lint_yaml_files:
  #   name: Lint project YAML files
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Install yamllint
  #       run: pip install yamllint
  #     - name: Lint YAML files
  #       run: yamllint .

  # reuse_lint:
  #   name: Check REUSE compliance
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: fsfe/reuse-action@v4
