# SPDX-FileCopyrightText: 2023 The Ossi Developers
#
# SPDX-License-Identifier: MIT
---
name: Pull Request Workflow
run-name: PR ${{ github.event.number }} - ${{ github.sha[0] }} ${{ github.sha[1] }} ${{ github.sha[2] }} ${{ github.sha[3] }} (${{ github.actor }})

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

jobs:
  run_e2e_tests:
    uses: ./.github/workflows/e2e-tests.yaml
  server_tests:
    uses: ./.github/workflows/server-tests.yaml
  lint_project:
    uses: ./.github/workflows/lint-project.yaml
  build_pr_containers:
    if: ${{ github.event.pull_request.draft == false }}
    uses: ./.github/workflows/build-and-publish.yaml
    with:
      registry: ghcr.io
      client_image_name: aalto-grades/aalto-grades-frontend-pr
      server_image_name: aalto-grades/aalto-grades-backend-pr
      image_tags: |
        type=raw,value=pr-${{ github.event.pull_request.number }}
        type=raw,value=sha-${{ github.event.pull_request.head.sha }}
