# SPDX-FileCopyrightText: 2022 The Aalto Grades Developers
#
# SPDX-License-Identifier: MIT

name: PR Workflow
run-name: ${{ github.actor }} pull request
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test_and_lint_client:
    name: Test and lint client
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test
      - name: Run linter
        run: npm run lint

  test_and_lint_server:
    name: Test and lint server
    runs-on: ubuntu-latest
    env:
      POSTGRES_PASSWORD: postgres
      SERVER_SKIP_CI: 1
    defaults:
      run:
        working-directory: ./server
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: docker-compose --file ../docker-tests/docker-compose.yaml up --abort-on-container-exit --exit-code-from back-end-test
      - name: Run linter
        run: npm run lint

  reuse_lint:
    name: Check REUSE compliance
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: fsfe/reuse-action@v1
