# SPDX-FileCopyrightText: 2023 The Ossi Developers
#
# SPDX-License-Identifier: MIT
---
name: Pull Request Workflow
run-name: ${{ github.head_ref }} pull request (${{ github.actor }})

on:
  pull_request:
    branches:
      - main
      - dev

jobs:
  run_e2e_tests:
    uses: ./.github/workflows/e2e-tests.yaml
  server_tests:
    uses: ./.github/workflows/server-tests.yaml
  lint_project:
    uses: ./.github/workflows/lint-project.yaml
