# SPDX-FileCopyrightText: 2022 The Aalto Grades Developers
#
# SPDX-License-Identifier: MIT
---

name: PR Workflow
run-name: ${{ github.actor }} pull request
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test_and_lint_client:
    name: Test and lint client
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test
      - name: Install linter dependencies
        run: npm --prefix .. ci
      - name: Run linter
        run: npm run lint

  test_and_lint_server:
    name: Test and lint server
    runs-on: self-hosted
    env:
      POSTGRES_PASSWORD: postgres
      NODE_ENV: test
      SERVER_SKIP_NPM_CI: 1
    defaults:
      run:
        working-directory: ./server
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm ci
      - name: Docker compose down
        run: docker-compose down --volumes --remove-orphans
      - name: Docker compose build
        run: docker-compose build --no-cache
      - name: Run tests
        run: docker-compose up --abort-on-container-exit --exit-code-from backend
      - name: Install linter dependencies
        run: npm --prefix .. ci
      - name: Run linter
        run: npm run lint

  lint_common:
    name: Lint common
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./common
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install linter dependencies
        run: npm --prefix .. ci
      - name: Run linter
        run: npm run lint

  lint_yaml_files:
    name: Lint project YAML files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install yamllint
        run: pip install yamllint
      - name: Lint YAML files
        run: yamllint .

  reuse_lint:
    name: Check REUSE compliance
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: fsfe/reuse-action@v1

  # lint_and_run_end_to_end_tests:
  #   name: Lint and run Cypress end-to-end tests
  #   runs-on: ubuntu-latest
  #   env:
  #     POSTGRES_PASSWORD: postgres
  #   defaults:
  #     run:
  #       working-directory: ./e2e-tests
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: actions/setup-node@v3
  #       with:
  #         node-version: '18'
  #     - name: Install dependencies
  #       run: npm ci
  #     - name: Run tests
  #       run: docker-compose up --build --abort-on-container-exit --exit-code-from cypress
  #     - name: Install linter dependencies
  #       run: npm --prefix .. ci
  #     - name: Run linter
  #       run: npm run lint
