# SPDX-FileCopyrightText: 2024 The Ossi Developers
#
# SPDX-License-Identifier: MIT
---
name: Server Tests
on:
  workflow_call:
    inputs: {}

jobs:
  server_tests:
    name: Run server tests
    runs-on: self-hosted
    env:
      NODE_ENV: test
    defaults:
      run:
        working-directory: ./server
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml
      - uses: pnpm/action-setup@v4
        with:
          version: 11
      - name: Docker compose down
        run: docker-compose down --volumes --remove-orphans
      - name: Run database
        run: docker-compose up -d database
      - name: Install dependencies
        working-directory: ./
        run: pnpm install --frozen-lockfile
      # - name: Install common dependencies
      #   run: pnpm --filter ./common install --frozen-lockfile
      - name: Build server
        run: pnpm run build
      - name: Migrate and seed database
        run: pnpm run migration:up && pnpm run seed:up
      - name: Run tests
        run: pnpm run citest
